update u-boot-install scripts and add package changelogs

diff --git a/packages/u-boot-orangepi-rk3588/debian/bin/u-boot-install-sata-mtd b/packages/u-boot-orangepi-rk3588/debian/bin/u-boot-install-sata-mtd
--- a/packages/u-boot-orangepi-rk3588/debian/bin/u-boot-install-sata-mtd
+++ b/packages/u-boot-orangepi-rk3588/debian/bin/u-boot-install-sata-mtd
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 set -eE 
-trap 'echo Error: in $0 on line $LINENO' ERR
 
 disk="/dev/mtd0"
 if [ ! -c "${disk}" ]; then
-    echo "$0: block device '${disk}' not found"
+    echo "$(basename "$0"): block device '${disk}' not found"
+    exit 1
 fi
-echo "$0: writing U-Boot to the SPI flash"
+echo "$(basename "$0"): writing U-Boot to the SPI flash"
 
 uboot_spi_image="/usr/lib/u-boot/u-boot-rockchip-spi-sata.bin"
 if [ ! -f "${uboot_spi_image}" ]; then
